//
//  TriadEphemerisProvider.swift
//  AstronomyKit
//
//  Created for AstronomyKit.
//  MIT Licence. See LICENCE file.
//

import Foundation

/// Major space agency / ephemeris research institution contributing to the numerical triad ensemble.
public enum TriadAgency: String, CaseIterable, Sendable, Identifiable {
    /// NASA Jet Propulsion Laboratory (United States) - DE series (e.g. DE442s).
    case us = "US"

    /// IMCCE / Observatoire de Paris (France) - INPOP series (e.g. INPOP21a).
    case fr = "FR"

    /// Institute of Applied Astronomy of the Russian Academy of Sciences (Russian Federation) - EPM series (e.g. EPM2021).
    case ru = "RU"

    /// Purple Mountain Observatory / Chinese Academy of Sciences (China) - PMOE series (e.g. PMOE).
    case cn = "CN"

    public var id: String { rawValue }

    /// Full descriptive institution name.
    public var institutionName: String {
        switch self {
        case .us:
            return "NASA NAIF / Jet Propulsion Laboratory (US)"
        case .fr:
            return "IMCCE – Observatoire de Paris (FR)"
        case .ru:
            return "IAA RAS – Institute of Applied Astronomy (RU)"
        case .cn:
            return "Purple Mountain Observatory / CAS (CN)"
        }
    }

    /// Corresponding primary dataset.
    public var dataset: EphemerisDataset {
        switch self {
        case .us: return .de442s
        case .fr: return .inpop21a
        case .ru: return .epm2021
        case .cn: return .pmoe
        }
    }
}

/// Semantic alias for numerical ephemeris agency ensembles (Triad / Tetrad).
public typealias EnsembleAgency = TriadAgency

/// Comprehensive metrological consensus details generated by the Triad numerical ensemble.
public struct TriadConsensusDetails: Sendable {
    /// The target Solar System body.
    public let body: SolarSystemBody

    /// The evaluation epoch in Julian Day (TDB).
    public let julianDay: JulianDay

    /// Consensus barycentric/heliocentric position in AU (ICRS/J2000).
    public let consensusPosition: Vector3D

    /// Consensus velocity in AU/day (ICRS/J2000).
    public let consensusVelocity: Vector3D

    /// 1-sigma physical dispersion across the contributing numerical models in kilometers.
    public let physicalUncertaintyKm: Double

    /// 1-sigma geocentric angular uncertainty in arcseconds (projected onto the celestial sphere).
    public let physicalUncertaintyArcsec: Double

    /// Maximum pairwise spatial discrepancy among all contributing agencies in kilometers.
    public let maxDiscrepancyKm: Double

    /// Individual positions computed by each contributing agency in AU.
    public let agencyPositions: [TriadAgency: Vector3D]

    /// Individual velocities computed by each contributing agency in AU/day.
    public let agencyVelocities: [TriadAgency: Vector3D]

    /// List of agencies that successfully contributed to this epoch.
    public let contributingAgencies: [TriadAgency]
}

/// Semantic alias for 4-agency ensemble consensus details (Tetrad).
public typealias TetradConsensusDetails = TriadConsensusDetails

/// Semantic alias for 4-agency ensemble provider (Tetrad).
public typealias TetradEphemerisProvider = TriadEphemerisProvider

/// High-definition ephemeris provider combining the major international numerical ephemerides:
/// - **US**: NASA JPL (`DE442s`, 1849–2150 CE)
/// - **FR**: IMCCE / Observatoire de Paris (`INPOP21a`, 1900–2100 CE)
/// - **RU**: IAA RAS (`EPM2021`, 1787–2214 CE)
/// - **CN**: PMO / CAS (`PMOE`, 1900–2100 CE)
///
/// ### Strict Numerical Exclusivity (No Analytical Fallback)
/// Unlike legacy convenience wrappers, `TriadEphemerisProvider` strictly enforces **numerical integrity**:
/// it never silently falls back to analytical theories (VSOP87 or ELP2000). If kernel data is absent or
/// outside the valid interpolation domain, it explicitly throws an ``EphemerisError``.
///
/// ### Metrological Consensus & Physical Uncertainty
/// In addition to standard ``EphemerisProvider`` conformance, this provider exposes
/// ``consensusDetails(for:at:)``, furnishing:
/// - Mean consensus position $\bar{\vec{r}}$ and velocity $\bar{\vec{v}}$.
/// - Empirical $1\sigma$ physical standard deviation between contributing agencies in kilometers.
/// - Geocentric angular uncertainty in arcseconds.
/// - Maximum discrepancy $\max \|\vec{r}_i - \vec{r}_j\|$ in kilometers.
public final class TriadEphemerisProvider: EphemerisProvider, Sendable {

    // MARK: - Constants

    /// Astronomical Unit in kilometers (IAU 2012 exact definition).
    public static let kmPerAU: Double = 149_597_870.700

    /// Arcseconds per radian.
    private static let arcsecPerRadian: Double = 206_264.806247096355

    // MARK: - Properties

    /// Active numerical ephemeris providers keyed by contributing agency.
    public let providers: [TriadAgency: any EphemerisProvider]

    // MARK: - Initialization

    /// Initializes a Triad/Tetrad provider with an explicit map of agency providers.
    ///
    /// - Parameter providers: Dictionary of configured numerical providers for US, FR, RU, and/or CN.
    /// - Throws: ``EphemerisError/dataFileNotFound(_:)`` if no providers are supplied.
    public init(providers: [TriadAgency: any EphemerisProvider]) throws {
        guard !providers.isEmpty else {
            throw EphemerisError.dataFileNotFound(
                "TriadEphemerisProvider requires at least one numerical ephemeris provider (US, FR, RU, or CN)."
            )
        }
        self.providers = providers
    }

    /// Convenience initializer accepting individual optional providers.
    ///
    /// - Parameters:
    ///   - us: NASA JPL provider (e.g. DE442s).
    ///   - fr: IMCCE provider (e.g. INPOP21a).
    ///   - ru: IAA RAS provider (e.g. EPM2021).
    ///   - cn: PMO / CAS provider (e.g. PMOE).
    /// - Throws: ``EphemerisError/dataFileNotFound(_:)`` if all parameters are `nil`.
    public convenience init(
        us: (any EphemerisProvider)? = nil,
        fr: (any EphemerisProvider)? = nil,
        ru: (any EphemerisProvider)? = nil,
        cn: (any EphemerisProvider)? = nil
    ) throws {
        var map: [TriadAgency: any EphemerisProvider] = [:]
        if let us { map[.us] = us }
        if let fr { map[.fr] = fr }
        if let ru { map[.ru] = ru }
        if let cn { map[.cn] = cn }
        try self.init(providers: map)
    }

    // MARK: - Consensus & Uncertainty Analysis

    /// Computes full metrological consensus details for a body at a given epoch.
    ///
    /// - Parameters:
    ///   - body: The target Solar System body.
    ///   - jd: Julian Day (TDB).
    /// - Returns: ``TriadConsensusDetails`` containing the consensus position, velocity, $1\sigma$ uncertainty, and pairwise spread.
    /// - Throws: ``EphemerisError`` if no numerical provider can evaluate the position at the requested epoch.
    public func consensusDetails(for body: SolarSystemBody, at jd: JulianDay) throws -> TriadConsensusDetails {
        if body == .sun {
            let active = Array(providers.keys).sorted(by: { $0.rawValue < $1.rawValue })
            var positions: [TriadAgency: Vector3D] = [:]
            var velocities: [TriadAgency: Vector3D] = [:]
            for agency in active {
                positions[agency] = .zero
                velocities[agency] = .zero
            }
            return TriadConsensusDetails(
                body: .sun,
                julianDay: jd,
                consensusPosition: .zero,
                consensusVelocity: .zero,
                physicalUncertaintyKm: 0.0,
                physicalUncertaintyArcsec: 0.0,
                maxDiscrepancyKm: 0.0,
                agencyPositions: positions,
                agencyVelocities: velocities,
                contributingAgencies: active
            )
        }

        var positions: [TriadAgency: Vector3D] = [:]
        var velocities: [TriadAgency: Vector3D] = [:]
        var lastError: Error?

        for (agency, provider) in providers {
            do {
                let sv = try provider.stateVector(for: body, at: jd)
                positions[agency] = sv.position
                velocities[agency] = sv.velocity
            } catch {
                lastError = error
            }
        }

        guard !positions.isEmpty else {
            if let lastError = lastError as? EphemerisError {
                throw lastError
            }
            throw EphemerisError.calculationFailed(
                "All Triad numerical providers failed to evaluate \(body.name) at JD \(jd.value): \(String(describing: lastError))"
            )
        }

        let contributing = Array(positions.keys).sorted(by: { $0.rawValue < $1.rawValue })
        let count = Double(contributing.count)

        // Arithmetic mean consensus
        var sumPos = Vector3D.zero
        var sumVel = Vector3D.zero
        for agency in contributing {
            sumPos = sumPos + positions[agency]!
            sumVel = sumVel + velocities[agency]!
        }
        let meanPos = sumPos / count
        let meanVel = sumVel / count

        // Uncertainty in km and maximum pairwise discrepancy
        var uncertaintyKm: Double = 0.0
        var maxDiscrepancyKm: Double = 0.0

        if contributing.count > 1 {
            var sumSquaredDevKm2: Double = 0.0
            for agency in contributing {
                let diffKm = (positions[agency]! - meanPos) * Self.kmPerAU
                sumSquaredDevKm2 += diffKm.lengthSquared
            }
            // Sample standard deviation (N - 1)
            let variance = sumSquaredDevKm2 / Double(contributing.count - 1)
            uncertaintyKm = sqrt(variance)

            // Pairwise discrepancies
            for i in 0..<contributing.count {
                for j in (i + 1)..<contributing.count {
                    let p1 = positions[contributing[i]]!
                    let p2 = positions[contributing[j]]!
                    let distKm = (p1 - p2).length * Self.kmPerAU
                    if distKm > maxDiscrepancyKm {
                        maxDiscrepancyKm = distKm
                    }
                }
            }
        }

        // Angular uncertainty in arcseconds (geocentric projection)
        var uncertaintyArcsec: Double = 0.0
        if uncertaintyKm > 0 && body != .earth {
            // Find Earth consensus position to determine geocentric distance
            let earthPos: Vector3D
            if let cachedEarth = try? evaluateEarthPosition(at: jd) {
                earthPos = cachedEarth
            } else {
                earthPos = meanPos // Fallback to barycentric distance if Earth cannot be resolved
            }
            let geocentricDistKm = (meanPos - earthPos).length * Self.kmPerAU
            if geocentricDistKm > 0 {
                let rad = uncertaintyKm / geocentricDistKm
                uncertaintyArcsec = rad * Self.arcsecPerRadian
            }
        }

        return TriadConsensusDetails(
            body: body,
            julianDay: jd,
            consensusPosition: meanPos,
            consensusVelocity: meanVel,
            physicalUncertaintyKm: uncertaintyKm,
            physicalUncertaintyArcsec: uncertaintyArcsec,
            maxDiscrepancyKm: maxDiscrepancyKm,
            agencyPositions: positions,
            agencyVelocities: velocities,
            contributingAgencies: contributing
        )
    }

    // MARK: - EphemerisProvider Conformance

    /// Heliocentric position of a Solar System body in AU (ICRS/J2000).
    public func position(for body: SolarSystemBody, at jd: JulianDay) throws -> Vector3D {
        try consensusDetails(for: body, at: jd).consensusPosition
    }

    /// Full 6D state vector (position in AU, velocity in AU/day) of a Solar System body (ICRS/J2000).
    public func stateVector(for body: SolarSystemBody, at jd: JulianDay) throws -> StateVector {
        let details = try consensusDetails(for: body, at: jd)
        return StateVector(position: details.consensusPosition, velocity: details.consensusVelocity)
    }

    // MARK: - Helper

    /// Evaluates Earth's consensus position for geocentric distance projection.
    private func evaluateEarthPosition(at jd: JulianDay) throws -> Vector3D {
        for provider in providers.values {
            if let pos = try? provider.position(for: .earth, at: jd) {
                return pos
            }
        }
        throw EphemerisError.calculationFailed("Could not resolve Earth position for angular projection")
    }
}
